server:
  port: 5050
spring:
  application:
    name: youtube-api
  security:
    oauth2:
      client:
        registration:
            google:
                client-id: 383806261434-csolcm1t04fuiq96ldn9lvkjn899nb95.apps.googleusercontent.com
                client-secret: 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
                scope:
                  - openid
                  - email
                  - profile
                redirect-uri: "http://localhost:5050/login/oauth2/code/google"
                authorization-grant-type: authorization_code
                client-name: Google
                provider: google

  servlet:
    multipart:
      max-file-size: 10000GB
      max-request-size: 10000GB

key: AIzaSyDdKzJQ78fu6FVvCKkXyMow-tq25J0u4tc
storage:
  bucket: home_runner


logging:
  level:
    com.example: DEBUG
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
    org.springframework.web: TRACE
    org.springframework.web.reactive: TRACE
